channels:
  - conda-forge
  - defaults

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
altair=5.5.0=pypi_0
annotated-types=0.7.0=pypi_0
anyio=4.6.2=py312h06a4308_0
argon2-cffi=21.3.0=pyhd3eb1b0_0
argon2-cffi-bindings=21.2.0=py312h5eee18b_0
asttokens=2.0.5=pyhd3eb1b0_0
async-lru=2.0.4=py312h06a4308_0
attrs=24.3.0=py312h06a4308_0
babel=2.11.0=py312h06a4308_0
beautifulsoup4=4.12.3=pyha770c72_1
bleach=6.2.0=py312h06a4308_0
blinker=1.9.0=pypi_0
bokeh=3.6.2=pypi_0
...
