[workspace]
channels = ['conda-forge']
name = 'vail_sec_forms'
platforms = ['linux-64']

[dependencies]
beautifulsoup4 = "4.12.3"
ipykernel = "6.29.5"
jupyter = "1.0.0"
jupyterlab = "4.2.5"
lxml = "5.3.0"
plotly = "5.24.1"
streamlit = "1.41.1"
pylint = ">=3.3.6,<4"
py2puml = ">=0.9.1,<0.10"
